import type { Metadata } from "next";

import { Space_Mono } from "next/font/google";
import { Lexend } from "next/font/google";
import { Space_Grotesk } from "next/font/google";

import "./globals.css";


const lexend = Lexend({
  variable: "--font-lexend",
  subsets:["latin"]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} bg-dark-blue antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
